t3/config/routes.rb
T3::Application.routes.draw do

  root to: "homes#index"

  resources :homes, path_names: { page: 'heimat' }

  resources :sessions, only: [:new, :create, :destroy]

  resources :homes

  resources :moves

  resources :games do
    post 'move/:square', to: 'games#move', as: :make_move
  end

  resources :users

  get '/signup', to: "users#new",        as: 'signup'
  get '/login',  to: "sessions#new",     as: 'login'
  delete '/logout', to: "sessions#destroy", as: 'logout'

end

t3/app/models/game.rb
class Game < ActiveRecord::Base
  # attr_accessible :name, :rating, :description, :win, :loss
  attr_accessible :user2_id

  belongs_to :user1, class_name: 'User'
  belongs_to :user2, class_name: 'User'

  has_many :moves
  after_initialize :setup_initial_values

  def board
    moves_made_array
  end

  def setup_initial_values
    @turn = 0
    @winning_positions = [[0, 4, 8], [3, 4, 5], [1, 4, 7], [2, 4, 6], [0, 1, 2], [0, 3, 6], [6, 7, 8], [2, 5, 8]]
  end

  def make_move(user, position)
    Move.create game_id: self.id, user_id: user.try(:id), position: position, token: which_token_next
  end

  # def has_started?
  #   if board == [ " ", " ", " ", " ", " ", " ", " ", " ", " " ]
  # end

  # def startWith
  #   @turn = 0
  # end

  def which_token_next
    moves.count.even? ? "X" : "O" 
    # if moves.count.even?
    #   return "x"
    # else
    #   return "o"
    # end
  end

  def position_is_occupied?(position)
    moves_made_array[position] != " "

  end

  def moves_made_array
    board = [ " ", " ", " ", " ", " ", " ", " ", " ", " " ]

    moves.map do |move|
      board[move.position] = move.token
    end
    board
  end

  def game_is_finished?
    !moves_made_array.include?(" ")  
  end

  def whose_turn
    moves.count.even? ? user1 : user2
  end

  def position_in_bounds?(position)
    (0..8).include?(position)
  end

  def hasWon?
    user = nil
    @winning_positions.each { |a|
      user = moves_made_array[a[0]]
      if user != " " && (moves_made_array[a[0]] == moves_made_array[a[1]]) && (moves_made_array[a[1]] == moves_made_array[a[2]])
        puts "Congratulations " + user + " you have won!"
        return user
      end
    }
    return false
  end

end

t3/app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @games = Game.all
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @games = Game.all
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @games = Game.all
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @games = Game.all
    @game = Game.new(params[:game])
    @game.user1 = current_user

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @games = Game.all
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @games = Game.all
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  def move
    @games = Game.all
    (redirect_to(login_path) and return) unless current_user

    @game = Game.find(params[:game_id])
    @move = @game.make_move current_user, params[:square].to_i

    if @move.errors.empty?
      redirect_to @game
    else
      flash.notice = @move.errors.full_messages.join(' ')
      redirect_to @game
    end
  end
end

t3/app/helpers/games_helper.rb
module GamesHelper
end

t3/app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="new">
  <p>
  <%= f.label :user2_id %>
  <%= f.collection_select :user2_id, (User.all - [current_user]), :id, :email %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

t3/app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

t3/app/views/games/index.html.erb
<h1>T3 Index</h1>

<% if can? :create, Game %>
<h4><%= link_to 'New Game', new_game_path %></h4>
<% end %>

<table id="index">
  <tr>
    <th>Game</th>
    <th></th>
    <th></th>
  </tr>



<% @games.each do |game| %>
  <tr>
    <td><%= game.id %></td>
    <td><%=game.user1.name%> vs. <%=game.user2.name%></td>
    <td><%= link_to 'Show', game %></td>
    <% if can? :create, Game %>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
  
</table>
  <br>

t3/app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

t3/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<div id="container" style="margin-left: 15%">

  <table id="game" >
    <tr>
      <td>
        <% if @game.position_is_occupied?(0) %>
          <%= @game.board[0]%>
        <% else %>
          <%= button_to " ", game_make_move_path(@game, 0), {:style => "background: #ffffff; width: 120px; height:135px" } %>
        <% end %>
      </td>
      <td>
        <% if @game.board[1] == " " %>
          <%= button_to " ", game_make_move_path(@game, 1), {:style => "background: #ffffff; width: 120px; height:135px" } %>
        <% else %>
          <%= @game.board[1]%>
        <% end %>
      </td>
      <td>
        <% if @game.board[2] == " " %>
          <%= button_to " ", game_make_move_path(@game, 2), {:style => "background: #ffffff; width: 120px; height:135px" } %>
        <% else %>
          <%= @game.board[2]%>
        <% end %>
      </td>
    </tr>

    <tr>
      <td>
        <% if @game.board[3] == " " %>
          <%= button_to " ", game_make_move_path(@game, 3), {:style => "background: #ffffff; width: 120px; height:135px" } %>
        <% else %>
          <%= @game.board[3]%>
        <% end %>
      </td>
      <td>
        <% if @game.board[4] == " " %>
          <%= button_to " ", game_make_move_path(@game, 4), {:style => "background: #ffffff; width: 120px; height:135px" } %>
        <% else %>
          <%= @game.board[4]%>
        <% end %>
      </td>
      <td>
        <% if @game.board[5] == " " %>
          <%= button_to " ", game_make_move_path(@game, 5), {:style => "background: #ffffff; width: 120px; height:135px" } %>
        <% else %>
          <%= @game.board[5]%>
        <% end %>
      </td>
    </tr>

    <tr>
      <td>
        <% if @game.board[6] == " " %>
          <%= button_to " ", game_make_move_path(@game, 6), {:style => "background: #ffffff; width: 120px; height:135px" } %>
        <% else %>
          <%= @game.board[6]%>
        <% end %>
      </td>
      <td>
        <% if @game.board[7] == " " %>
          <%= button_to " ", game_make_move_path(@game, 7), {:style => "background: #ffffff; width: 120px; height:135px" } %>
        <% else %>
          <%= @game.board[7]%>
        <% end %>
      </td>
      <td>
        <% if @game.board[8] == " " %>
          <%= button_to " ", game_make_move_path(@game, 8), {:style => "background: #ffffff; width: 120px; height:135px" } %>
        <% else %>
          <%= @game.board[8]%>
        <% end %>
      </td>
    </tr>
  </table>


<br>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>


 </div>
 <br>