t3/config/routes.rb
T3::Application.routes.draw do

  root to: "homes#index"

  resources :homes, path_names: { page: 'heimat' }

  resources :sessions, only: [:new, :create, :destroy]

  resources :homes

  resources :moves

  resources :games do
    post 'move/:square', to: 'games#move', as: :make_move
  end

  resources :users

  get '/signup', to: "users#new",        as: 'signup'
  get '/login',  to: "sessions#new",     as: 'login'
  delete '/logout', to: "sessions#destroy", as: 'logout'

end

t3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>T3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <header>
      <nav>

        <a href='/'><img src="http://icons.iconarchive.com/icons/icondesigner.net/hyperion/256/Games-icon.png"></a>

        <ul>
          <li><%= link_to "Home", '/' %></li> | 
          <li><%= link_to "Users", users_path%></li> | 
          <li><%= link_to "Games", games_path%></li>


      <li>
      <% if current_user %>
        | <%= link_to 'Logout', session_path(session), method: :delete, data: {confirm: 'Are you sure?'} %>
        | User:
        <%= current_user.email %>
                <% flash.each do |name, message| %>
          <%= message %>
        <% end %>
      <% else %>
        | <%= link_to 'Login', login_path %>
        | logged out!
      <% end %>
      </li>
      </ul>
      </nav>

      <p>
        <% if current_user %>
          Games in progress: 
          <% @games.each do |game| %>
            <% if game.user1.name == current_user.name %>
              <%= link_to game.id, game %>
            <% end %>
          <% end %>
        <% end %>
      </p>

    </header>
  <div id="content">
    <%= yield %>
  </div>

  <footer>
    <p>&copy; Tom 2014</p>
  </footer>
  </div>
</body>
</html>